### ISSUE TITLE
Another way.

### ISSUE THREAD

**Issue by crm76** [fidian/leapfrog-my-pal#1]
Hi. Thanks for the effort.

I think I have found another way to delete the name from the device.

Using the LeapFrog Connect software, I set the name to "none".  Since it can't find a pronunciation, LeapFrog Connect states the pal will spell the name instead. However, after it was synced, it did not spell n-o-n-e. Instead it didn't say anything where it would normally say a name. While it still have to be synced with favorite color, food, etc., using none as the name appears to be a way to clear a child's name from the unit.

**Comment by fidian** [comment]
What if you press the paws so that it sings the kid's name? There's one song where it spells out the name and I expect it would spell out "N", "O", "N", "E" for that song. Maybe not during the "Hello, _____." phrases because I think it just plays whatever audio is associated with the name that's in memory.

Your solution might remove the kid's name, but one could just reset it to "John" and achieve nearly the same effect. I was looking to perform a factory reset. Changing the name to "None" is not the same end result as receiving a toy that has no favorite colors, no best friend's name, no embedded songs.

This issue doesn't make a lot of sense to me. Because your suggestion doesn't do the wipe and does not seem to have any request of this project, I will be closing it. If I missed the point, please comment or open a new issue.
